version: "2"

linters:
  settings:
    errcheck:
      disable-default-exclusions: true
  exclusions:
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"

run:
  timeout: 5m
