ALTER TABLE tags ADD COLUMN color      TEXT;
ALTER TABLE tags ADD COLUMN group_name TEXT;
ALTER TABLE tags ADD COLUMN created_at DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00';
ALTER TABLE tags ADD COLUMN last_used_at DATETIME;
