package service

import (
	"context"
	"fmt"
	"strings"
	"time"

	"damask/server/internal/apperr"
	"damask/server/internal/auth"
	"damask/server/internal/repository"
)

// WorkspaceDTO is the output of WorkspaceService methods.
type WorkspaceDTO struct {
	ID                       string
	Name                     string
	IngestToken              *string
	VersionRetentionCount    int64
	EventLogRetentionDays    int64
	DownloadLogRetentionDays int64
	IconAssetID              *string
	IconVersionID            *string
	ExifKeep                 bool
	ExifKeepGps              bool
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

// WorkspaceMeDTO bundles workspace + user + role + asset count for the /me endpoint.
type WorkspaceMeDTO struct {
	Workspace       *WorkspaceDTO
	UserID          string
	UserEmail       string
	UserName        string
	UserCreatedAt   time.Time
	Role            string
	TotalAssetCount int64
}

// WorkspaceWithRoleDTO is a workspace summary with the caller's role.
type WorkspaceWithRoleDTO struct {
	ID          string
	Name        string
	Role        string
	MemberCount int64
	AssetCount  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// MemberDTO is the output representation of a workspace member.
type MemberDTO struct {
	UserID   string
	Email    string
	Name     string
	Role     string
	JoinedAt time.Time
}

// InviteDTO is the output representation of a workspace invite.
type InviteDTO struct {
	ID          string
	InviteToken string
	Email       string
	Role        string
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

// UpdateWorkspaceParams is the input for WorkspaceService.Update.
type UpdateWorkspaceParams struct {
	VersionRetentionCount *int64
	ExifKeep              *bool
	ExifKeepGps           *bool
}

// CreateInviteParams is the input for WorkspaceService.CreateInvite.
type CreateInviteParams struct {
	Email string
	Role  auth.Role
}

// AcceptInviteParams is the input for WorkspaceService.AcceptInvite.
type AcceptInviteParams struct {
	Token        string
	Name         string
	PasswordHash string
	UserID       string // pre-generated by caller
}

// AcceptInviteResult is returned by WorkspaceService.AcceptInvite.
type AcceptInviteResult struct {
	UserID        string
	WorkspaceID   string
	UserEmail     string
	UserName      string
	UserCreatedAt time.Time
	InviterID     string
	InviteRole    string
}

type workspaceService struct {
	workspaces repository.WorkspaceRepository
	users      repository.UserRepository
}

// NewWorkspaceService returns a WorkspaceService.
func NewWorkspaceService(workspaces repository.WorkspaceRepository, users repository.UserRepository) WorkspaceService {
	return &workspaceService{workspaces: workspaces, users: users}
}

func (s *workspaceService) Get(ctx context.Context, workspaceID string) (*WorkspaceDTO, error) {
	ws, err := s.workspaces.GetByID(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	return toWorkspaceDTO(ws), nil
}

func (s *workspaceService) Update(ctx context.Context, workspaceID string, p UpdateWorkspaceParams) (*WorkspaceDTO, error) {
	existing, err := s.workspaces.GetByID(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	if p.VersionRetentionCount != nil {
		existing.VersionRetentionCount = *p.VersionRetentionCount
	}
	if p.ExifKeep != nil {
		existing.ExifKeep = *p.ExifKeep
	}
	if p.ExifKeepGps != nil {
		existing.ExifKeepGps = *p.ExifKeepGps
	}
	updated, err := s.workspaces.Update(ctx, existing)
	if err != nil {
		return nil, err
	}
	return toWorkspaceDTO(updated), nil
}

func (s *workspaceService) Me(ctx context.Context, workspaceID, userID string) (*WorkspaceMeDTO, error) {
	ws, err := s.workspaces.GetByID(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	user, err := s.users.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	member, err := s.workspaces.GetMember(ctx, workspaceID, userID)
	if err != nil {
		return nil, fmt.Errorf("not a member of this workspace: %w", apperr.ErrForbidden)
	}
	assetCount, _ := s.workspaces.CountAssets(ctx, workspaceID)
	return &WorkspaceMeDTO{
		Workspace:       toWorkspaceDTO(ws),
		UserID:          user.ID,
		UserEmail:       user.Email,
		UserName:        user.Name,
		UserCreatedAt:   user.CreatedAt,
		Role:            member.Role,
		TotalAssetCount: assetCount,
	}, nil
}

func (s *workspaceService) ListForUser(ctx context.Context, userID string) ([]WorkspaceWithRoleDTO, error) {
	rows, err := s.workspaces.ListByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}
	out := make([]WorkspaceWithRoleDTO, len(rows))
	for i, r := range rows {
		memberCount, _ := s.workspaces.CountMembers(ctx, r.ID)
		assetCount, _ := s.workspaces.CountAssets(ctx, r.ID)
		out[i] = WorkspaceWithRoleDTO{
			ID:          r.ID,
			Name:        r.Name,
			Role:        r.Role,
			MemberCount: memberCount,
			AssetCount:  assetCount,
			CreatedAt:   r.CreatedAt,
			UpdatedAt:   r.UpdatedAt,
		}
	}
	return out, nil
}

func (s *workspaceService) CountAssets(ctx context.Context, workspaceID string) (int64, error) {
	return s.workspaces.CountAssets(ctx, workspaceID)
}

func (s *workspaceService) GetMember(ctx context.Context, workspaceID, userID string) (*MemberDTO, error) {
	m, err := s.workspaces.GetMember(ctx, workspaceID, userID)
	if err != nil {
		return nil, err
	}
	return toMemberDTO(m), nil
}

func (s *workspaceService) ListMembers(ctx context.Context, workspaceID string) ([]MemberDTO, error) {
	members, err := s.workspaces.ListMembers(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	out := make([]MemberDTO, len(members))
	for i, m := range members {
		out[i] = *toMemberDTO(m)
	}
	return out, nil
}

func (s *workspaceService) RemoveMember(ctx context.Context, workspaceID, callerID, targetUserID string) error {
	if callerID == targetUserID {
		return fmt.Errorf("cannot remove yourself: %w", apperr.ErrInvalidInput)
	}
	members, err := s.workspaces.ListMembers(ctx, workspaceID)
	if err != nil {
		return err
	}
	ownerCount := 0
	for _, m := range members {
		if m.Role == string(auth.Owner) {
			ownerCount++
		}
	}
	for _, m := range members {
		if m.UserID == targetUserID && m.Role == string(auth.Owner) && ownerCount <= 1 {
			return fmt.Errorf("cannot remove the last owner: %w", apperr.ErrInvalidInput)
		}
	}
	return s.workspaces.DeleteMember(ctx, workspaceID, targetUserID)
}

func (s *workspaceService) UpdateMemberRole(ctx context.Context, workspaceID, callerID, targetUserID, role string) error {
	if callerID == targetUserID && role != string(auth.Owner) {
		members, err := s.workspaces.ListMembers(ctx, workspaceID)
		if err != nil {
			return err
		}
		ownerCount := 0
		for _, m := range members {
			if m.Role == string(auth.Owner) {
				ownerCount++
			}
		}
		if ownerCount <= 1 {
			return fmt.Errorf("cannot demote the last owner: %w", apperr.ErrInvalidInput)
		}
	}
	return s.workspaces.UpdateMemberRole(ctx, workspaceID, targetUserID, role)
}

func (s *workspaceService) CreateInvite(ctx context.Context, workspaceID, callerID string, p CreateInviteParams) (*InviteDTO, error) {
	inv, err := s.workspaces.CreateInvite(ctx, repository.Invite{
		WorkspaceID: workspaceID,
		Email:       p.Email,
		Role:        string(p.Role),
		InvitedBy:   callerID,
	})
	if err != nil {
		return nil, err
	}
	return toInviteDTO(inv, true), nil
}

func (s *workspaceService) ListInvites(ctx context.Context, workspaceID string) ([]InviteDTO, error) {
	invites, err := s.workspaces.ListPendingInvites(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	out := make([]InviteDTO, len(invites))
	for i, inv := range invites {
		out[i] = *toInviteDTO(inv, false)
	}
	return out, nil
}

func (s *workspaceService) DeleteInvite(ctx context.Context, workspaceID, inviteID string) error {
	return s.workspaces.DeleteInvite(ctx, workspaceID, inviteID)
}

func (s *workspaceService) AcceptInvite(ctx context.Context, p AcceptInviteParams) (*AcceptInviteResult, error) {
	inv, err := s.workspaces.GetInviteByToken(ctx, p.Token)
	if err != nil {
		return nil, fmt.Errorf("invalid or expired invite token: %w", apperr.ErrNotFound)
	}

	newUser, err := s.users.Create(ctx, repository.User{
		ID:           p.UserID,
		Email:        inv.Email,
		PasswordHash: p.PasswordHash,
		Name:         p.Name,
	})
	if err != nil {
		if strings.Contains(err.Error(), "UNIQUE constraint failed") {
			return nil, fmt.Errorf("email already in use: %w", apperr.ErrConflict)
		}
		return nil, fmt.Errorf("could not create user: %w", err)
	}

	invitedBy := inv.InvitedBy
	if err := s.workspaces.CreateMember(ctx, repository.Member{
		WorkspaceID: inv.WorkspaceID,
		UserID:      p.UserID,
		Role:        inv.Role,
		InvitedBy:   &invitedBy,
	}); err != nil {
		return nil, err
	}

	if err := s.workspaces.AcceptInvite(ctx, inv.ID); err != nil {
		return nil, err
	}

	return &AcceptInviteResult{
		UserID:        p.UserID,
		WorkspaceID:   inv.WorkspaceID,
		UserEmail:     inv.Email,
		UserName:      p.Name,
		UserCreatedAt: newUser.CreatedAt,
		InviterID:     inv.InvitedBy,
		InviteRole:    inv.Role,
	}, nil
}

func toWorkspaceDTO(ws repository.Workspace) *WorkspaceDTO {
	return &WorkspaceDTO{
		ID:                       ws.ID,
		Name:                     ws.Name,
		IngestToken:              ws.IngestToken,
		VersionRetentionCount:    ws.VersionRetentionCount,
		EventLogRetentionDays:    ws.EventLogRetentionDays,
		DownloadLogRetentionDays: ws.DownloadLogRetentionDays,
		IconAssetID:              ws.IconAssetID,
		IconVersionID:            ws.IconVersionID,
		ExifKeep:                 ws.ExifKeep,
		ExifKeepGps:              ws.ExifKeepGps,
		CreatedAt:                ws.CreatedAt,
		UpdatedAt:                ws.UpdatedAt,
	}
}

func toMemberDTO(m repository.Member) *MemberDTO {
	return &MemberDTO{
		UserID:   m.UserID,
		Email:    m.Email,
		Name:     m.Name,
		Role:     m.Role,
		JoinedAt: m.JoinedAt,
	}
}

func toInviteDTO(inv repository.Invite, includeToken bool) *InviteDTO {
	d := &InviteDTO{
		ID:        inv.ID,
		Email:     inv.Email,
		Role:      inv.Role,
		ExpiresAt: inv.ExpiresAt,
		CreatedAt: inv.CreatedAt,
	}
	if includeToken {
		d.InviteToken = inv.Token
	}
	return d
}
