import {
  AudioLines,
  Camera,
  Crop,
  EraserIcon,
  Film,
  Maximize2,
  Music,
  RefreshCw,
  Scissors,
  Shapes,
  Sparkles,
  Stamp,
  Video,
} from '@lucide/svelte'
import type { VariantToolDef } from './types'

export const ALL_VARIANT_TOOLS: VariantToolDef[] = [
  {
    key: 'resize',
    label: 'variant_tool_resize',
    sublabel: 'variant_tool_resize_sub',
    icon: Maximize2,
    showFor: (m) => m.startsWith('image/'),
  },
  {
    key: 'crop',
    label: 'variant_tool_crop',
    sublabel: 'variant_tool_crop_sub',
    icon: Crop,
    showFor: (m) => m.startsWith('image/'),
  },
  {
    key: 'smart_crop',
    label: 'variant_tool_smart_crop',
    sublabel: 'variant_tool_smart_crop_sub',
    icon: Scissors,
    showFor: (m) => m.startsWith('image/'),
  },
  {
    key: 'convert',
    label: 'variant_tool_convert',
    sublabel: 'variant_tool_convert_sub',
    icon: Shapes,
    showFor: (m) => m.startsWith('image/'),
  },
  {
    key: 'image_with_prompt',
    label: 'variant_tool_ai_transform',
    sublabel: 'variant_tool_ai_transform_sub',
    icon: Sparkles,
    showFor: (m) => m.startsWith('image/'),
  },
  {
    key: 'watermark',
    label: 'variant_tool_watermark',
    sublabel: 'variant_tool_watermark_sub',
    icon: Stamp,
    showFor: (m) => m.startsWith('image/'),
  },
  {
    key: 'bg_remove',
    label: 'variant_tool_bg_remove',
    sublabel: 'variant_tool_bg_remove_sub',
    icon: EraserIcon,
    showFor: (m) => m.startsWith('image/'),
  },
  {
    key: 'video_transcode',
    label: 'variant_tool_video_transcode',
    sublabel: 'variant_tool_video_transcode_sub',
    icon: Video,
    showFor: (m) => m.startsWith('video/'),
  },
  {
    key: 'video_watermark',
    label: 'variant_tool_video_watermark',
    sublabel: 'variant_tool_video_watermark_sub',
    icon: Film,
    showFor: (m) => m.startsWith('video/'),
  },
  {
    key: 'video_capture_image',
    label: 'variant_tool_video_capture',
    sublabel: 'variant_tool_video_capture_sub',
    icon: Camera,
    showFor: (m) => m.startsWith('video/'),
  },
  {
    key: 'audio_extract',
    label: 'variant_tool_audio_extract',
    sublabel: 'variant_tool_audio_extract_sub',
    icon: Music,
    showFor: (m) => m.startsWith('video/'),
  },
  {
    key: 'audio_transcode',
    label: 'variant_tool_audio_transcode',
    sublabel: 'variant_tool_audio_transcode_sub',
    icon: Music,
    showFor: (m) => m.startsWith('audio/'),
  },
  {
    key: 'audio_normalize',
    label: 'variant_tool_audio_normalize',
    sublabel: 'variant_tool_audio_normalize_sub',
    icon: AudioLines,
    showFor: (m) => m.startsWith('audio/'),
  },
]
